# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e5db79467935d2016844545cb35bf611c1faef1f36f8086515c07ba4b786c8790e2af226a0c3d6885ffb283105569dad298becee1c133c24f426b2e6fb7e40b

test:
  secret_key_base: f4f55db9fdecd96a640c2430ffcc5d6a6d9793d917d98820a3c7e781f94bf74b496c95c8890f89adc5e001f57154cb303a3f31ac09a72bd07fe7461b6b096742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
